crates/clorinde/src/type_registrar.rs

This fixes https://github.com/cornucopia-rs/cornucopia/issues/253 by adding Type::BPCHAR to the list of string types.
I apologize for the noise I caused.

add bpchar to string types

---

crates/clorinde/src/lib.rs

The `settings` parameter are named `config` in the API now.

docs: rename settings parameter to config

---

crates/clorinde/src/codegen/cargo.rs

Custom types may reference std types like `String`, in which case there
won't necessarily be a "ctypes" crate. Detect this case to avoid adding
the dependency.

Only depend on "ctypes" crate if it is referenced

---

crates/clorinde/src/type_registrar.rs

This is useful when mapping a custom type to a std Rust type, like so:
```toml
[types.mapping]
"public.ulid" = { rust_type = "String", is_copy = false }
```
(It's [hard](https://github.com/pksunkara/pgx_ulid/issues/27) to provide a ToSql/FromSql implementation for ulid.)
An alternative to hardcoding known std types would be to add an option
for the borrowed version of a type in "types.mapping".

Detect borrowed type based on std Rust types

---

crates/clorinde/src/codegen/cargo.rs
examples/basic_async/basic_async_codegen/Cargo.toml
examples/custom_types/custom_types_codegen/Cargo.toml
tests/codegen/codegen/Cargo.toml

Having
```
wasm-async = ["tokio-postgres/js", "chrono/wasmbind", "time/wasm-bindgen"]
```
Would enable both `chrono` and `time`, which would result in definition
conflicts.
This PR uses `?` syntax to enable only the feature if something else
enables the optional dependency.

Don't force enable optional dependencies if wasm-async is enabled

---

crates/clorinde/src/type_registrar.rs
tests/codegen/codegen/src/queries/stress.rs
tests/codegen/queries/stress.sql
tests/codegen/schema.sql
tests/codegen/src/main.rs

resolves #23.
This adds the extension types and additional test cases for `citext` and `ltree` following the correct types as described by the corresponding traits of `FromSql` and `ToSql` in `postgres-types` ([code reference](https://github.com/sfackler/rust-postgres/blob/master/postgres-types/src/lib.rs#L709)).

feat: add citext and other extension friends

---

crates/clorinde/src/config.rs

Adds support for `publish: ["repo1"]` in clorinde.toml.
See here for more info.
https://doc.rust-lang.org/cargo/reference/manifest.html#the-publish-field

fix: publish to specific repo wasn't supported in clorinde.toml

---

.gitattributes
clorinde/src/codegen/vfs.rs
clorinde/src/config.rs
clorinde/src/lib.rs
examples/custom_types/clorinde.toml
examples/custom_types/custom_types_codegen/Cargo.toml
examples/custom_types/custom_types_codegen/kafstel.txt
examples/custom_types/kafstel.txt

resolves #7 and #45.
- Adds a new option to `clorinde.toml`: `static` that lists files you want copied to the generated directory. Has ability to hard link files instead if they are large and you don't want them copied.
- Adds a `.gitattributes` and marks all codegen files in the repo as generated. This should make reviews easier, while keeping the ability to track diffs.

feat; add static files config

---

benches/generated/src/queries/bench.rs
benches/queries/bench.sql
clorinde/src/codegen/queries.rs
clorinde/src/parser.rs
clorinde/src/prepare_queries.rs
tests/codegen/codegen/src/queries/syntax.rs
tests/codegen/queries/syntax.sql
tests/codegen/src/main.rs

Wanted to learn how the parsing works, figured https://github.com/cornucopia-rs/cornucopia/issues/165 would be a good issue to tackle.
- Adds `---` comments after query declarations that get added as doc strings (`///`) to the generated Rust code.
```sql
--! insert_user
--- This performs a bulk insert using unnest
--- because VALUES isn't supported for parameterized bulk inserts
INSERT INTO users (name, hair_color)
SELECT unnest(:names::text[]) as name,
unnest(:hair_colors::text[]) as hair_color;
```
Generates:
```rust
/// This performs a bulk insert using unnest
/// because VALUES isn't supported for parameterized bulk inserts
pub fn insert_user() -> InsertUserStmt {
// ...
}
```
- Fixes a bug with sql comments being added to the query (and added tests). With the query now having …

feat: add query doc strings

---

Cargo.lock
clorinde/src/codegen/queries.rs
clorinde/src/codegen/types.rs
clorinde/src/config.rs
clorinde/src/parser.rs
clorinde/src/prepare_queries.rs
docs/src/configuration.md
docs/src/writing_queries/type_annotations.md
examples/basic_async/basic_async_codegen/src/queries/module_2.rs
examples/basic_async/queries/module_2.sql
examples/custom_types/clorinde.toml
examples/custom_types/ctypes/Cargo.toml
examples/custom_types/ctypes/src/date.rs
examples/custom_types/custom_types_codegen/Cargo.toml
examples/custom_types/custom_types_codegen/src/queries/module_2.rs
examples/custom_types/custom_types_codegen/src/types.rs
examples/custom_types/queries/module_2.sql
tests/codegen/queries/named.sql
tests/codegen/queries/nullity.sql
tests/integration/fixtures/codegen/examples.toml

resolves #56.
adds ability to specify derive traits on generated row struct through:
- `types.derive-traits` config: adds to all structs.
```toml
[types]
derive-traits = ["Hash", "serde::Deserialize"]
```
- Type annotations: adds to that specific type.
```sql
--: Author() : Hash, serde::Deserialize
--! list_authors : Author
select * from Author;
```

feat: add derive traits

---

benches/generated/src/types.rs
clorinde/src/codegen/types.rs
examples/auto_build/auto_build_codegen/src/types.rs
examples/basic_async/basic_async_codegen/src/types.rs
examples/basic_async_wasm/basic_async_wasm_codegen/src/types.rs
examples/basic_sync/basic_sync_codegen/src/types.rs
examples/custom_types/custom_types_codegen/src/types.rs
tests/codegen/codegen/src/types.rs

The following generated code block breaks the rust-analyzer (for me):
```rust
#[cfg(feature = "time")]
pub mod time {
pub type Timestamp = time::PrimitiveDateTime;
pub type TimestampTz = time::OffsetDateTime;
pub type Date = time::Date;
pub type Time = time::Time;
}
```
And I don't see any possilbe issues with changing it to have the same kind of config as chrono.

fix(codegen): make "chrono" and "time" features mutually exclusive

---

clorinde/src/codegen/queries.rs
clorinde/src/codegen/types.rs
clorinde/src/config.rs
clorinde/src/prepare_queries.rs
clorinde/src/type_registrar.rs

This PR implements a solution for issue #79 by adding the ability to define custom serialization
attributes for fields based on their PostgreSQL type.
1. Add support for custom `attributes` field in `TypeMapping::Detailed`
2. Add accessor method for type attributes in config
3. Implement attributes in field generation for row structs and composite types
4. Apply attributes to all borrowed structs where applicable
Users can now customize the serialization of timestamp fields as follows:
```toml
[types.mapping]
"pg_catalog.timestamptz" = {
rust-type = "crate::types::time::TimestampTz",
attributes = [
"serde(with = \"crate::serde_utils\")",
]
}
```
This configuration adds `#[serde(with = "crate::serde_utils")]` to any field of type timestamptz,
providing greater control over serialization.

feat: allow custom field attributes in type mappings

---

clorinde/src/codegen/queries.rs
clorinde/src/read_queries.rs

This change allows Clorinde to handle SQL files organized in subdirectories by recursively traversing the directory structure and mapping it to a corresponding module hierarchy in the generated Rust code.
For example, a file at `queries/users/roles.sql` will be compiled to `src/queries/users/roles.rs` and properly exposed through module hierarchy.
The implementation:
- Adds recursive directory traversal in read_queries.rs
- Tracks both the file name and full module path
- Generates appropriate mod.rs files for each directory level
- Converts directory separators to Rust module separators

feat: support for directory-based SQL files mapped to module hierarchy

---

docs/src/introduction/introduction.md

Fix dead link to examples in the book.

Fix broken link to examples page

---

clorinde/src/cli.rs
clorinde/src/conn.rs

This pull request introduces a new feature to allow specifying a custom PostgreSQL search path for queries in the `clorinde` CLI tool. The changes include adding a new `search_path` option, updating the handling of the `Action::Live` variant, and implementing a utility function to set the search path in the database client.
* **Added `search_path` option to `Action::Live`**: A new optional `search_path` parameter was introduced in the `Action::Live` variant of the CLI to enable users to specify a custom search path for PostgreSQL queries. (`clorinde/src/cli.rs`, [clorinde/src/cli.rsR23-R26](diffhunk://#diff-415929db97e3fa65c6902e0f9cb88ba0bb9df4bc8b5dcb65bc9755a7325370dcR23-R26))
* **Updated `run` function to handle `search_path`**: The `run` function now sets the search path for the …

Add search_path option to Live action and set in Postgres client

---

clorinde/src/codegen/queries.rs
clorinde/src/config.rs

- Adds a new `params-only` configuration option that makes the `bind()` method private
- Forces users to use the safer `params()` method with named parameter structs
- Prevents errors from incorrect parameter ordering in positional bind() calls
- Added `params_only: bool` field to `Config` struct with default value `false`
- Added `params_only()` method to `ConfigBuilder`
- Modified code generation to conditionally set bind() visibility based on `params_only` flag
- When `params_only = true` and query has named parameters, bind() is generated as private

feat: add params-only mode to make bind() private

---

Cargo.lock
benches/generated/Cargo.toml
benches/generated/src/array_iterator.rs
examples/auto_build/auto_build_codegen/Cargo.toml
examples/auto_build/auto_build_codegen/src/array_iterator.rs
examples/basic_async/basic_async_codegen/Cargo.toml
examples/basic_async/basic_async_codegen/src/array_iterator.rs
examples/basic_async_wasm/basic_async_wasm_codegen/Cargo.toml
examples/basic_async_wasm/basic_async_wasm_codegen/src/array_iterator.rs
examples/basic_sync/basic_sync_codegen/Cargo.toml
examples/basic_sync/basic_sync_codegen/src/array_iterator.rs
examples/custom_types/db/custom_types_codegen/Cargo.toml
examples/custom_types/db/custom_types_codegen/src/array_iterator.rs
src/codegen/cargo.rs
src/codegen/client.rs
tests/codegen/codegen/Cargo.toml
tests/codegen/codegen/src/array_iterator.rs

postgres is unconditionally added as a non-optional dependency, which prevents generated crates from being compiled in wasm with --features wasm-async.
Make it an optional dependency and include fallible_iterator as a non-optional dependency.
Fixes #135

Fix WASM compilation

---

src/config.rs

For some reason #159 fails with `error[E0308]: mismatched types` at compile time. I'm not sure why this error occurs when updating toml from 0.8 to 0.9, as I had compared [`toml::Value`](https://docs.rs/toml/latest/toml/enum.Value.html) across the two versions and they are the same. But this fixes it.
```
cargo run --package test_integration -- --apply-codegen --podman
```
I tested it both with toml 0.8 and 0.9 (applying the changes in #159). Everything passed in both versions.

fix: specify concrete type for cargo_toml::Package

---

src/codegen/cargo.rs
src/config.rs

Sorry for another PR right after #165 was merged, but I thought more on how I fixed the error in #165 (specifying `toml::Value` to not use the default `cargo_toml::Value`) and figured I should have done it the other way around: change the `toml::Value`s to the default `cargo_toml::Value`. The two types are the exact same (behind the type aliases):
- https://docs.rs/cargo_toml/latest/cargo_toml/enum.Value.html
- https://docs.rs/toml/latest/toml/enum.Value.html
This offers two benefits:
1. Clorinde users who want to call [`ConfigBuilder.manifest`](https://docs.rs/clorinde/latest/clorinde/config/struct.ConfigBuilder.html#method.manifest) will only need `cargo_toml` to construct the Manifest. Currently they also need `toml` because of the `toml::Value` in Manifest. (would this be considered a …

fix: use default type arg for cargo_toml::Manifest

---

.github/workflows/main.yaml
docs/src/writing_queries/type_annotations.md
rust-toolchain.toml
src/codegen/queries.rs
src/parser.rs
src/prepare_queries.rs
tests/codegen/codegen/src/queries/attributes.rs
tests/codegen/queries/attributes.sql

Fixes #176
Add support for `--&` syntax to specify custom attributes exclusively for borrowed struct variants. This allows separate attribute configuration for owned and borrowed structs.
Updated `attributes.sql` in codegen test.

feat!: add custom attrs for borrowed structs
